name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: hamprod.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t hamprod.azurecr.io/cv-chatbot-api:${{ github.run_number }} .
        docker push hamprod.azurecr.io/cv-chatbot-api:${{ github.run_number }}
